name: iOS Build

on:
  push:
    branches:
      - test_cases
  pull_request:
    branches:
      - test_cases
      
jobs:
   build:
    name: test
    runs-on: macos-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: iOS Build
          run: |
            xcodebuild -scheme fanta -destination "platform=iOS Simulator,name=iPhone 13"
